# Generated by Django 3.0.14 on 2022-09-20 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_cpu',
            fields=[
                ('id_cpu', models.AutoField(db_column='IdCpu', primary_key=True, serialize=False)),
                ('cpu_name', models.CharField(blank=True, db_column='CpuName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Tb_CPU',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tb_device_type',
            fields=[
                ('id_device_type', models.IntegerField(db_column='IdDeviceType', primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, db_column='TypeName', max_length=100)),
                ('type_description', models.CharField(db_column='TypeDescription', max_length=200)),
            ],
            options={
                'db_table': 'Tb_Device_Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tb_org',
            fields=[
                ('id_org', models.AutoField(db_column='IdOrg', primary_key=True, serialize=False)),
                ('org_name', models.CharField(blank=True, db_column='OrgName', max_length=100, null=True)),
                ('org_tax_id', models.CharField(blank=True, db_column='OrgTaxID', max_length=50, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=20, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('addres', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('postal', models.CharField(blank=True, db_column='Postal', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Tb_Org',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tb_os',
            fields=[
                ('id_os', models.IntegerField(db_column='IdOS', primary_key=True, serialize=False)),
                ('os_name', models.CharField(blank=True, db_column='OsName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Tb_OS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tb_people',
            fields=[
                ('email_people', models.EmailField(db_column='EmailPeople', max_length=200, primary_key=True, serialize=False)),
                ('name_people', models.CharField(blank=True, db_column='NamePeople', max_length=100, null=True)),
                ('id_org', models.ForeignKey(db_column='IdOrg', on_delete=django.db.models.deletion.PROTECT, to='crud.tb_org')),
            ],
            options={
                'db_table': 'Tb_People',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tb_provisioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_org', models.IntegerField(blank=True, db_column='IdOrg', null=True)),
                ('id_site', models.IntegerField(blank=True, db_column='IdSite', null=True)),
                ('id_zone', models.IntegerField(blank=True, db_column='IdZone', null=True)),
                ('id_device', models.IntegerField(blank=True, db_column='IdDevice', null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Tb_provisioning',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tb_sites',
            fields=[
                ('id_site', models.AutoField(db_column='IdSite', primary_key=True, serialize=False)),
                ('site_name', models.CharField(blank=True, db_column='SiteName', max_length=100, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=20, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('postal', models.CharField(blank=True, db_column='Postal', max_length=15, null=True)),
            ],
            options={
                'db_table': 'Tb_Sites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tb_zones',
            fields=[
                ('id_zone', models.AutoField(db_column='IdZone', primary_key=True, serialize=False)),
                ('zone_name', models.CharField(blank=True, db_column='ZoneName', max_length=100, null=True)),
                ('id_org', models.ForeignKey(db_column='IdOrg', on_delete=django.db.models.deletion.PROTECT, to='crud.tb_org')),
                ('id_site', models.ForeignKey(db_column='IdSite', on_delete=django.db.models.deletion.PROTECT, to='crud.tb_sites')),
            ],
            options={
                'db_table': 'Tb_Zones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tb_permissions',
            fields=[
                ('id_permission', models.AutoField(db_column='IdPermission', primary_key=True, serialize=False)),
                ('id_org', models.IntegerField(blank=True, db_column='IdOrg', null=True)),
                ('id_site', models.IntegerField(blank=True, db_column='IdSite', null=True)),
                ('id_zone', models.IntegerField(blank=True, db_column='IdZone', null=True)),
                ('id_device', models.IntegerField(blank=True, db_column='IdDevice', null=True)),
                ('email_people', models.ForeignKey(db_column='EmailPeople', on_delete=django.db.models.deletion.CASCADE, to='crud.tb_people')),
            ],
            options={
                'db_table': 'Tb_Permissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tb_devices',
            fields=[
                ('id_device', models.BigAutoField(db_column='IdDevice', primary_key=True, serialize=False)),
                ('ip_from', models.CharField(blank=True, db_column='IpFrom', max_length=100, null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated')),
                ('id_cpu', models.ForeignKey(db_column='IdCpu', on_delete=django.db.models.deletion.PROTECT, to='crud.tb_cpu')),
                ('id_device_type', models.ForeignKey(db_column='IdDeviceType', on_delete=django.db.models.deletion.PROTECT, to='crud.tb_device_type')),
                ('id_os', models.ForeignKey(db_column='IdOS', on_delete=django.db.models.deletion.PROTECT, to='crud.tb_os')),
                ('id_zone', models.ForeignKey(db_column='IdZone', on_delete=django.db.models.deletion.PROTECT, to='crud.tb_zones')),
            ],
            options={
                'db_table': 'Tb_Devices',
                'managed': True,
            },
        ),
    ]
