# Generated by Django 3.0.14 on 2022-09-29 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_permissions_app',
            fields=[
                ('id_permission_app', models.AutoField(db_column='IdPermissionApp', primary_key=True, serialize=False)),
                ('name_app', models.CharField(blank=True, db_column='NameApp', max_length=100, null=True)),
                ('level', models.IntegerField(blank=True, db_column='Level', null=True)),
                ('email_people', models.ForeignKey(db_column='EmailPeople', on_delete=django.db.models.deletion.CASCADE, to='crud.tb_people')),
            ],
            options={
                'db_table': 'Tb_Permissions_App',
                'managed': True,
            },
        ),
    ]
